name: Upload Rust Package

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose
  deploy:
    needs: build
    # commit contains a tag => deploy
    if: startsWith( github.ref, 'refs/tags/v' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install cargo-edit
        run: cargo install cargo-edit  
      - name: Set VERSION environment variable
        run: |
          echo GitHub_ref: $GITHUB_REF
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          echo Version: $VERSION
          VERSION="${VERSION//v}"
          echo Clean Version: $VERSION
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Set version in Cargo.toml
        run: cargo set-version ${{ env.VERSION }}
      - name: Cargo Login
        run: cargo login ${{ secrets.CRATES_IO_API_KEY }}        
      - name: Create Crates.io package
        run: cargo publish
